### ISSUE TITLE
Website Harmful Software Warning

### ISSUE THREAD

**Issue by joshbruce** [fontlabcom/getgo-fonts#2]
I haven't received this warning in the past. Receiving it now.

<img width="736" alt="Screenshot 2023-04-26 at 5 01 30 PM" src="https://user-images.githubusercontent.com/15252830/234701858-f4a374d6-fc25-4adc-abc1-469fc41ae2ba.png">

I thought you'd like to know.

**Comment by twardoch** [comment]
Which URL was this? Browswr? OS? What does "Show Details" say?

**Comment by joshbruce** [comment]
macOS - Ventura 13.3.1

Fair questions - maybe Google doesn't like having someone else with downloadable fonts? (I cloned the repo instead for now.)

Every time I try to download a font. The sample pages work fine. Soon as I hit the download button...

<img width="700" alt="Screenshot showing Safari version as 16.4" src="https://user-images.githubusercontent.com/15252830/234717276-cd099642-aafa-4c10-a8b1-7d77b09aaca5.png">
 
<img width="896" alt="Screenshot showing Firefox version as 102.0.2" src="https://user-images.githubusercontent.com/15252830/234717481-aec2a8ab-b753-4ae4-95f7-333255757ac4.png">

I no longer have a Chrome-based browser.

**Comment by joshbruce** [comment]
URL of transparency report from Google: https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fdowngit.github.io%2F%23%2Fhome%3Furl%3Dhttps:%2F%2Fgithub.com%2Ffontlabcom%2Fgetgo-fonts%2Fblob%2Fmain%2Fgetgo-fonts%2Fcc0%2Focra%2Focra.vfj

**Comment by twardoch** [comment]
We updated all download links on https://fontlabcom.github.io/getgo-fonts/
